
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-service
  namespace: default
  uid: 015ea674-0271-4979-820c-53c6fd387629
  resourceVersion: '22838'
  generation: 3
  creationTimestamp: '2024-12-12T20:04:17Z'
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"order-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"order-service"}},"template":{"metadata":{"labels":{"app":"order-service"}},"spec":{"containers":[{"env":[{"name":"ORDER_QUEUE_HOSTNAME","value":"rabbitmq"},{"name":"ORDER_QUEUE_PORT","value":"5672"},{"name":"ORDER_QUEUE_USERNAME","value":"username"},{"name":"ORDER_QUEUE_PASSWORD","value":"password"},{"name":"ORDER_QUEUE_NAME","value":"orders"},{"name":"FASTIFY_ADDRESS","value":"0.0.0.0"}],"image":"ramymohamed/order-service-l8:latest","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":3,"periodSeconds":3},"name":"order-service","ports":[{"containerPort":3000}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":3,"periodSeconds":5},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"1m","memory":"50Mi"}},"startupProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":20,"periodSeconds":10}}],"initContainers":[{"command":["sh","-c","until
      nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2;
      done;"],"image":"busybox","name":"wait-for-rabbitmq","resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"1m","memory":"50Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2024-12-12T20:04:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"order-service"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"FASTIFY_ADDRESS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ORDER_QUEUE_HOSTNAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ORDER_QUEUE_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ORDER_QUEUE_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ORDER_QUEUE_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"ORDER_QUEUE_USERNAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":3000,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:startupProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:initContainers:
                .: {}
                k:{"name":"wait-for-rabbitmq"}:
                  .: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:nodeSelector: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kubectl-rollout
      operation: Update
      apiVersion: apps/v1
      time: '2024-12-12T21:13:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
    - manager: kubectl-set
      operation: Update
      apiVersion: apps/v1
      time: '2024-12-12T21:13:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"order-service"}:
                  f:image: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-12-12T21:13:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-12-12T21:13:12Z'
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            - sh
            - '-c'
            - >-
              until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2;
              done;
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 1m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - name: order-service
          image: aakashsidhu/order-service:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: ORDER_QUEUE_HOSTNAME
              value: rabbitmq
            - name: ORDER_QUEUE_PORT
              value: '5672'
            - name: ORDER_QUEUE_USERNAME
              value: username
            - name: ORDER_QUEUE_PASSWORD
              value: password
            - name: ORDER_QUEUE_NAME
              value: orders
            - name: FASTIFY_ADDRESS
              value: 0.0.0.0
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 1m
              memory: 50Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-12-12T20:05:28Z'
      lastTransitionTime: '2024-12-12T20:05:28Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-12-12T21:13:43Z'
      lastTransitionTime: '2024-12-12T20:04:17Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "order-service-79749749bb" has successfully progressed.
